softname: nodejs
softshowname: NodeJS
softofficialhomelink: https://nodejs.org/en/
softofficialhomelink_cn: https://nodejs.org/zh-cn/
softofficialdownloadlink: https://nodejs.org/en/download/
softofficialdownloadlink_cn: https://nodejs.org/zh-cn/download/
softsource: https://github.com/nodejs/node
# 软件图标
softlogo: http://pc1.gtimg.com/guanjia/images/7d/5b/7d5b3c4911f5157e2e2e778d8840d3cd.jpg
# 软件列表页banner图
softbanner: http://pc1.gtimg.com/guanjia/images/42/8b/428b48f4f4687434577386d6d7350060.jpg
# 软件一句话描述
softshortcomment: JavaScript 运行时
# 软件介绍
softcomment: Node.js® 是一个基于 Chrome V8 引擎 的 JavaScript 运行时。
# 软件分类,可以多个
softcategory:
    - env
softicon:
    - free
softspecialtip: 特别说明
# 是否需要同步
softsync: false
# [可选]是否显示在软件列表页,默认为true , 可选值: true false
softshowinlist: false
