softname: postman
softshowname: Postman
softofficialhomelink: https://www.getpostman.com
softofficialdownloadlink: https://www.postman.com/downloads/
# 软件图标
softlogo: statics/soft/postman/logo.png
# 软件列表页banner图
softbanner: statics/soft/postman/banner.png
# 软件一句话描述
softshortcomment: API调试
# 软件介绍
softcomment: API接口开发调试工具
softspecialtip: 特别说明
# 软件分类,可以多个
softcategory:
    - tool
softicon:
    - paid
# 是否需要同步
softsync: true
# [可选]是否显示在软件列表页,默认为true , 可选值: true false
softshowinlist: true
# [可选]是否显示软件平台,适合平台只有少量几个的时候,很多平台(5个以上)不要开,默认false
softshowplatform: true
release:
    win:
        platform: win
        platformshowname: Windows
        link: https://dl.pstmn.io/changelog?channel=stable&platform=win
        linktype: json
        linkrequestmethod: GET
        # 获取远程版本最大数量,可以控制丢弃一些老的版本,默认50
        getversionmaxnum: 6
        # 展示到页面时版本最大数量,多余的版本会显示在归档中,默认5
        showversionmaxnum: 5
        # 是否按版本类型进行分类显示,默认为false
        showgroupbychannel: true
        rule:
            datatype: array
            root: changelog
            version: name
            time: createdAt
            channel: channel
            notes: notes
            features: notes.Features
            gennotespagepath: app/{{softname}}/{{platform}}/{{version}}/releasenotes.html
            download:
                root: assets
                filename:
                    type: field
                    value: name
                filehash:
                    type: field
                    value: hash
                filesize: size
                fileurl:
                    type: field
                    value: url
                fileuploadprefix:
                    type: string
                    value: app/{{softname}}/win/{{version}}/
    mac:
        platform: mac
        platformshowname: MacOS
        link: https://dl.pstmn.io/changelog?channel=stable&platform=osx
        linktype: json
        linkrequestmethod: GET
        # 获取远程版本最大数量,可以控制丢弃一些老的版本,默认50
        getversionmaxnum: 6
        # 展示到页面时版本最大数量,多余的版本会显示在归档中,默认5
        showversionmaxnum: 5
        # 是否按版本类型进行分类显示,默认为false
        showgroupbychannel: true
        rule:
            datatype: array
            root: changelog
            version: name
            time: createdAt
            notes: notes
            features: notes.Features
            download:
                root: assets
                filename:
                    type: field
                    value: name
                filehash:
                    type: field
                    value: hash
                filesize: size
                fileurl:
                    type: field
                    value: url
                fileuploadprefix:
                    type: string
                    value: app/{{softname}}/mac/{{version}}/
    linux:
        platform: linux
        platformshowname: Linux(x64)
        link: https://dl.pstmn.io/changelog?channel=stable&platform=linux
        linktype: json
        linkrequestmethod: GET
        # 获取远程版本最大数量,可以控制丢弃一些老的版本,默认50
        getversionmaxnum: 6
        # 展示到页面时版本最大数量,多余的版本会显示在归档中,默认5
        showversionmaxnum: 5
        # 是否按版本类型进行分类显示,默认为false
        showgroupbychannel: true
        rule:
            datatype: array
            root: changelog
            version: name
            time: createdAt
            notes: notes
            features: notes.Features
            download:
                root: assets
                filename:
                    type: field
                    value: name
                filehash:
                    type: field
                    value: hash
                filesize: size
                fileurl:
                    type: field
                    value: url
                fileuploadprefix:
                    type: string
                    value: app/{{softname}}/linux/{{version}}/
