name: Test

on: [push]

jobs:
  测试:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 获取IP地址
      run: curl ipinfo.io

    - name: PHP版本
      run: |
        php -v
      env:
        QINIU_ACCESS_KEY: ${{ secrets.QINIU_ACCESS_KEY }}
        QINIU_SECRET_KEY: ${{ secrets.QINIU_SECRET_KEY }}
        QINIU_ACCESS_KEY_1: ${{ secrets.QINIU_ACCESS_KEY_1 }}
        QINIU_SECRET_KEY_1: ${{ secrets.QINIU_SECRET_KEY_1 }}
        QINIU_ACCESS_KEY_2: ${{ secrets.QINIU_ACCESS_KEY_2 }}
        QINIU_SECRET_KEY_2: ${{ secrets.QINIU_SECRET_KEY_2 }}