name: Test

on: [push]

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Deps
      run: |
        sudo apt-get update
        sudo apt-get install -y php-curl aria2

    - name: Test softsync
      run: |
        php -r "echo system('ls -l')";
      env:
        LANZOU_USERNAME: ${{ secrets.LANZOU_USERNAME }}
        LANZOU_PASSWORD: ${{ secrets.LANZOU_PASSWORD }}
