name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
          python-version: 3.7
    - name: Install LanZouCloud-API
      run: pip install lanzou-api
    - name: Install RAR
      run: |
       sudo apt-get install rar
       whereis rar
