name: Update Site

on:
  push:
    branches:
      - master

jobs:
  _UpdateSite_:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 获取IP地址&PHP版本&当前时间
      run: |
        curl ipinfo.io
        php -v
        php -r "echo date('Y-m-d H:i:s');"
    - name: 更新基础数据
      run: |
        php sync/updatesite.php
      env:
        QINIU_ACCESS_KEY: ${{ secrets.QINIU_ACCESS_KEY }}
        QINIU_SECRET_KEY: ${{ secrets.QINIU_SECRET_KEY }}
    - name: 安装SSH key for Gitee
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa # optional
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        #config: ${{ secrets.CONFIG }} # ssh_config; optional
    - name: Push更新到Gitee,并更新Gitee Pages
      run: |
        chmod u+x ./deploy/deploy2gitee.sh
        ./deploy/deploy2gitee.sh
      env:
        GITEE_ACCESS_TOKEN: ${{ secrets.GITEE_ACCESS_TOKEN }}
    - name: 提交文件到当前仓库
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git status
        git commit -m "🤖bot: Auto Update" -a
    - name: Push更新到当前仓库
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
